import numpy as np
x = np.array([3,2,1,8,4])
y = np.array([4, 7, 9, 8, 3])
print("Array A")
print(x)
print("Array B")
print(y)
print("A>B")
print(np.greater(x, y))
print("A>=B")
print(np.greater_equal(x,y))
print("A<B")
print(np.less(x,y))
print("A<=B")
print(np.less_equal(x,y))
